services:
  server:
    container_name: nextjs_app
    build:
      context: .
    environment:
      - NODE_ENV=production
      - POSTGRES_HOST=db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=example
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src:/usr/src/app/src
    networks:
      - app_network

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: example
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "root", "-d", "example"]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - app_network

volumes:
  db-data:

networks:
  app_network:
